version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - wordpress:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:6.4-php8.2-fpm-alpine
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', 6379);
        define('WP_CACHE', true);
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_MAX_MEMORY_LIMIT', '512M');
        define('DISABLE_WP_CRON', true);
        define('WP_POST_REVISIONS', 5);
        define('EMPTY_TRASH_DAYS', 7);
        define('WP_AUTO_UPDATE_CORE', false);
    volumes:
      - wordpress:/var/www/html
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/zz-wordpress.conf
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:lts
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
             --innodb-buffer-pool-size=1G
             --innodb-buffer-pool-instances=2
             --innodb-flush-method=O_DIRECT
             --innodb-log-file-size=256M
             --innodb-flush-log-at-trx-commit=2
             --skip-log-bin

  redis:
    image: redis:7.2-alpine
    volumes:
      - redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  wordpress:
  mysql:
  redis:
