services:
  mysql:
    image: "mysql:8.4.4"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - "mysql_data:/var/lib/mysql"
    command: "mysqld --innodb-buffer-pool-size=1G --innodb-buffer-pool-instances=2 --innodb-flush-method=O_DIRECT --innodb-log-file-size=256M --innodb-flush-log-at-trx-commit=2 --skip-log-bin --port=3306"
    networks:
      - wordpress_net
    restart: unless-stopped

  nginx:
    image: "nginx:1.25-alpine"
    volumes:
      - "wordpress_data:/var/www/html"
      - "./conf.d:/etc/nginx/conf.d"
    depends_on:
      - wordpress
    networks:
      - wordpress_net
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-nginx.loadbalancer.server.port=80"

  wordpress:
    image: "wordpress:6.4-php8.2-fpm-alpine"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', 6379);
        define('WP_CACHE', true);
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_MAX_MEMORY_LIMIT', '512M');
        define('DISABLE_WP_CRON', true);
        define('WP_POST_REVISIONS', 5);
        define('EMPTY_TRASH_DAYS', 7);
        define('WP_AUTO_UPDATE_CORE', false);
    volumes:
      - "wordpress_data:/var/www/html"
      - "./php-fpm.conf:/usr/local/etc/php-fpm.d/zz-wordpress.conf"
    depends_on:
      - mysql
      - redis
    networks:
      - wordpress_net
    restart: unless-stopped

  redis:
    image: "redis:7.2-alpine"
    volumes:
      - "redis_data:/data"
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
    command: "redis-server /usr/local/etc/redis/redis.conf"
    networks:
      - wordpress_net
    restart: unless-stopped

volumes:
  wordpress_data:
  mysql_data:
  redis_data:

networks:
  wordpress_net:
    driver: bridge
